# Site settings
title: Lingfei LU | HKUST
SEOTitle: Lingfei LU | HKUST
email: lingfei.lu@connect.ust.hk
description: "Lingfei Lu's Personal Website"
url: "lingfei-daniel-lu.github.io"
baseurl: ""
github_repo: "https://github.com/lingfei-daniel-lu/lingfei-daniel-lu.github.io.git"
theme: minima
markdown: kramdown
